[package]
autotests = false
name = "calyx-oracle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
calyx-assay = { workspace = true }
calyx-anneal = { workspace = true }
calyx-aster = { workspace = true }
calyx-core = { workspace = true }
calyx-forge = { workspace = true }
calyx-ledger = { workspace = true }
calyx-lodestar = { workspace = true }
calyx-paths = { workspace = true }
calyx-ward = { workspace = true }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
